### PR TITLE
Fix PHP 8+ compat issues

### LINKED ISSUE #124: compatibility issue with php8.2

### PR DESCRIPTION
**Pull request by sanmai**
Fixes #124

I did three things here:
- Added missing properties.
- Added variable types and expanded argument types to include `null` where appropriate.
- Fixed one issue with possibly missing array key.

### CODE REVIEW

File: lib/Tumblr/API/RequestHandler.php [hunk 1]
```diff
@@ -96,7 +107,7 @@ public function request($method, $path, $options)
         );
         $oauth->sign_request($this->signatureMethod, $this->consumer, $this->token);
         $authHeader = $oauth->to_header();
-        $pieces = explode(' ', $authHeader, 2);
+        $pieces = explode(' ', $authHeader, 2) + [1 => ''];
```
Comment (sanmai) [inline lib/Tumblr/API/RequestHandler.php:110]: The only code change here: to guard against `$authHeader` having no space.

**Review by diegoaer — APPROVED** [review]
Looks good!
